### ISSUE TITLE
is this still necessary?

### ISSUE THREAD

**Issue by exalted** [cam-stitt/atom-syntax-settings#21]
I have a feeling that atom now supports grammar/syntax based settings natively.

Any ideas please?

Thank you.

**Comment by tekkub** [comment]
Atom core has per-syntax settings now: https://discuss.atom.io/t/different-tab-size-depending-on-language/1523

You can access them by going to Settings > Packages, finding the package for your language, then clicking "Settings" for it.

**Comment by exalted** [comment]
:cool: I guess, I will go ahead and remove this package from my atom. Thanks for the great work so far!

**Comment by cam-stitt** [comment]
Good to see they finally added it. I haven't really been actively advancing this package either. It's also good too see they actually used some of my concepts.
